name: Unittests 

on: 
  pull_request:
    branches: 
      - development* 
  
  push:
    branches:
      - development* 

jobs:
  test:
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        go-version: [1.18.x]
    
    steps:
      - name: Setup 
        uses: actions/setup-go@v2 
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout 
        uses: actions/checkout@v2 
      - name: Run all tests
        run: |  
          go test ./... -coverprofile c.out
      - name: Coverage 
        run: | 
          go tool cover -func=c.out